quarkus:
  application:
    name: mediawiki-mcp
  http:
    port: 8081
    test-port: 0
  smallrye-health:
    root-path: /health

mediawiki:
  url: ${MEDIAWIKI_URL:https://wiki.howarth.eu/api.php}
  bot-user: ${MEDIAWIKI_BOT_USER:}
  bot-password: ${MEDIAWIKI_BOT_PASSWORD:}

"%test":
  mediawiki:
    bot-user: test-user
    bot-password: test-password