FROM eclipse-temurin:21-jre-alpine
WORKDIR /deployments
COPY target/quarkus-app/lib/ lib/
COPY target/quarkus-app/*.jar ./
COPY target/quarkus-app/app/ app/
COPY target/quarkus-app/quarkus/ quarkus/
EXPOSE 8081
USER 1001
CMD ["java", "-jar", "quarkus-run.jar"]
